#!/usr/bin/env python3
"""
Full data audit for the Section-1 failure-modes + BIO-replication pipeline.

Answers, top to bottom:
  1. Universe & cohort filtering — how many trials/programs at each step
  2. Enrichment coverage — what fraction of drugs and indications are classified
  3. Classification confidence — distribution of high/medium/low across LLM outputs
  4. Sanity checks — known drugs (pembrolizumab, atorvastatin, etc.) classified correctly
  5. Orphans — drugs in cohort programs missing from drug_bio_class, etc.
  6. Approvals linkage — every FDA approval traceable to a program?
  7. Distribution sanity — modality mix, therapeutic area mix
  8. Comparison to published — key transition rates vs BIO 2021 / Wong 2019 / Cook 2014
  9. Silent buckets — how many "presumptive fail" outcomes rely on inference vs direct signal

Writes a markdown report to `data/data_audit.md` and prints a summary to stdout.
"""
from __future__ import annotations
import os, sys
import psycopg2
import pandas as pd

HERE = os.path.dirname(os.path.abspath(__file__))
DATA = os.path.join(HERE, "..", "data")
DB = ("postgresql://neondb_owner:npg_Snpr6yPT9sOE@ep-late-smoke-amionchh-pooler."
      "c-5.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require")


def q(conn, sql: str, **kw) -> pd.DataFrame:
    return pd.read_sql(sql, conn, params=kw or None)


def to_md(df: pd.DataFrame) -> str:
    """Simple markdown table renderer — no `tabulate` dependency."""
    cols = list(df.columns)
    header = "| " + " | ".join(str(c) for c in cols) + " |"
    sep = "|" + "|".join("---" for _ in cols) + "|"
    rows = []
    for _, r in df.iterrows():
        cells = []
        for v in r:
            if isinstance(v, float):
                cells.append(f"{v:,.1f}")
            elif isinstance(v, (int,)) or (isinstance(v, float) and v.is_integer()):
                cells.append(f"{int(v):,}")
            else:
                cells.append(str(v) if v is not None else "")
        rows.append("| " + " | ".join(cells) + " |")
    return "\n".join([header, sep] + rows)


def section(md: list, title: str, body: str) -> None:
    md.append(f"\n## {title}\n\n{body}\n")


def main():
    conn = psycopg2.connect(DB)
    md = ["# Data audit — Section 1 pipeline\n",
          "Generated by `analyses/audit_data.py`. All numbers pulled live from the "
          "predictive-validity Neon DB (`preclin.*` schema).\n"]

    # ─── 1. Universe & cohort filtering ────────────────────────────────────
    print("(1) Universe & cohort filtering")
    df = q(conn, """
      SELECT 'CT.gov industry Ph1-3 trials 2015-2025' AS filter, COUNT(*) AS n
      FROM public.trials
      WHERE sponsor_type='INDUSTRY' AND phase ~ '(PHASE1|PHASE2|PHASE3)'
        AND start_date >= '2015-01-01' AND start_date < '2026-01-01'
      UNION ALL SELECT 'Trials linked to a program in preclin.program_trial',
        COUNT(DISTINCT nct_id) FROM preclin.program_trial
      UNION ALL SELECT '  ... status = COMPLETED',
        COUNT(DISTINCT t.nct_id) FROM public.trials t
        JOIN preclin.program_trial pt USING(nct_id) WHERE t.status='COMPLETED'
      UNION ALL SELECT '  ... status = TERMINATED/WITHDRAWN/SUSPENDED',
        COUNT(DISTINCT t.nct_id) FROM public.trials t
        JOIN preclin.program_trial pt USING(nct_id)
        WHERE t.status IN ('TERMINATED','WITHDRAWN','SUSPENDED')
      UNION ALL SELECT '  ... status = ACTIVE / RECRUITING / NOT-YET',
        COUNT(DISTINCT t.nct_id) FROM public.trials t
        JOIN preclin.program_trial pt USING(nct_id)
        WHERE t.status IN ('RECRUITING','ACTIVE_NOT_RECRUITING',
                           'ENROLLING_BY_INVITATION','NOT_YET_RECRUITING')
      UNION ALL SELECT 'Programs (drug × indication × sponsor)', COUNT(*) FROM preclin.program
      UNION ALL SELECT '  ... highest_phase >= 1', COUNT(*)
        FROM preclin.program WHERE highest_phase >= 1
      UNION ALL SELECT '  ... highest_phase >= 2', COUNT(*)
        FROM preclin.program WHERE highest_phase >= 2
      UNION ALL SELECT '  ... highest_phase >= 3', COUNT(*)
        FROM preclin.program WHERE highest_phase >= 3
      UNION ALL SELECT 'Programs with outcome_broad=approved', COUNT(*)
        FROM preclin.program_outcome WHERE outcome_broad='approved'
    """)
    print(df.to_string(index=False))
    section(md, "1. Universe & cohort filtering",
            to_md(df))

    # ─── 2. Terminated-by-2026 filter breakdown ───────────────────────────
    print("\n(2) Terminated-by-2026 filter — what's kept vs dropped")
    df = q(conn, """
      WITH activity AS (
        SELECT pt.program_id,
          BOOL_OR(t.status IN ('RECRUITING','ACTIVE_NOT_RECRUITING',
                               'ENROLLING_BY_INVITATION','NOT_YET_RECRUITING')) AS active,
          MAX(COALESCE(t.completion_date, t.primary_completion_date, t.start_date)) AS latest
        FROM preclin.program_trial pt JOIN public.trials t USING(nct_id)
        GROUP BY pt.program_id
      )
      SELECT
        CASE
          WHEN po.outcome_broad = 'unknown' THEN 'dropped: outcome=unknown'
          WHEN COALESCE(a.active, FALSE) THEN 'dropped: has active trial'
          WHEN po.outcome_broad IN ('phase1_only','presumptive_fail_ph2',
                                    'presumptive_efficacy_fail_ph3')
               AND (a.latest IS NULL OR a.latest >= '2024-07-01')
               THEN 'dropped: presumptive-fail, <18mo quiet'
          ELSE 'KEPT: terminated by 2026'
        END AS bucket,
        COUNT(*) AS n_programs
      FROM preclin.program p
      JOIN preclin.program_outcome po ON po.program_id = p.program_id
      LEFT JOIN activity a ON a.program_id = p.program_id
      WHERE p.highest_phase >= 1
      GROUP BY bucket ORDER BY n_programs DESC;
    """)
    print(df.to_string(index=False))
    section(md, "2. \"Terminated by 2026\" filter — kept vs dropped",
            to_md(df))

    # ─── 3. Enrichment coverage ────────────────────────────────────────────
    print("\n(3) Enrichment coverage")
    df = q(conn, """
      SELECT 'Indications (all)' AS pop, COUNT(*) AS n,
             COUNT(ibc.indication_id) AS classified,
             ROUND(100.0 * COUNT(ibc.indication_id) / NULLIF(COUNT(*),0), 1) AS pct
      FROM preclin.indication i
      LEFT JOIN preclin.indication_bio_class ibc USING(indication_id)
      UNION ALL SELECT 'Drugs (all)',
        COUNT(*), COUNT(dbc.drug_id),
        ROUND(100.0 * COUNT(dbc.drug_id) / NULLIF(COUNT(*),0), 1)
      FROM preclin.drug d
      LEFT JOIN preclin.drug_bio_class dbc USING(drug_id)
      UNION ALL SELECT 'Drugs (in-cohort — used by at least 1 program)',
        COUNT(DISTINCT d.drug_id), COUNT(DISTINCT dbc.drug_id),
        ROUND(100.0 * COUNT(DISTINCT dbc.drug_id) / NULLIF(COUNT(DISTINCT d.drug_id),0), 1)
      FROM preclin.drug d JOIN preclin.program p ON p.drug_id = d.drug_id
      LEFT JOIN preclin.drug_bio_class dbc ON dbc.drug_id = d.drug_id;
    """)
    print(df.to_string(index=False))
    section(md, "3. Enrichment coverage",
            to_md(df))

    # ─── 4. Classification confidence + source distribution ────────────────
    print("\n(4) Classification confidence")
    df = q(conn, """
      SELECT 'indication' AS tbl, confidence,
             COUNT(*) AS n, ROUND(100.0*COUNT(*)/SUM(COUNT(*)) OVER(),1) AS pct
      FROM preclin.indication_bio_class GROUP BY confidence
      UNION ALL SELECT 'drug', confidence, COUNT(*),
             ROUND(100.0*COUNT(*)/SUM(COUNT(*)) OVER(),1)
      FROM preclin.drug_bio_class GROUP BY confidence
      ORDER BY tbl, confidence NULLS LAST;
    """)
    print(df.to_string(index=False))
    section(md, "4. Classification confidence",
            to_md(df))

    df = q(conn, """
      SELECT 'indication' AS tbl, source, COUNT(*) AS n FROM preclin.indication_bio_class
      GROUP BY source
      UNION ALL SELECT 'drug', source, COUNT(*) FROM preclin.drug_bio_class GROUP BY source
      ORDER BY tbl, n DESC;
    """)
    print(df.to_string(index=False))
    section(md, "4b. Classification source ladder",
            to_md(df))

    # ─── 5. Distribution sanity — modalities ───────────────────────────────
    print("\n(5a) Modality distribution")
    df = q(conn, """
      SELECT modality, COUNT(*) AS n_drugs,
             ROUND(100.0*COUNT(*)/SUM(COUNT(*)) OVER(),1) AS pct
      FROM preclin.drug_bio_class GROUP BY modality ORDER BY n_drugs DESC;
    """)
    print(df.to_string(index=False))
    section(md, "5a. Modality distribution (all classified drugs)",
            to_md(df))

    print("\n(5b) Therapeutic area distribution")
    df = q(conn, """
      SELECT bio_area, COUNT(*) AS n_indications
      FROM preclin.indication_bio_class GROUP BY bio_area ORDER BY n_indications DESC;
    """)
    print(df.to_string(index=False))
    section(md, "5b. Therapeutic area distribution",
            to_md(df))

    # ─── 6. Spot-checks: known drugs classified correctly ─────────────────
    print("\n(6a) Known-drug spot check")
    df = q(conn, """
      SELECT d.normalized_name AS drug, dbc.modality, dbc.novelty_class,
             dbc.source, dbc.confidence
      FROM preclin.drug d
      LEFT JOIN preclin.drug_bio_class dbc USING(drug_id)
      WHERE LOWER(d.normalized_name) IN (
        'pembrolizumab','sacituzumab govitecan','semaglutide','atorvastatin',
        'onasemnogene abeparvovec','tisagenlecleucel','patisiran','inclisiran',
        'palbociclib','osimertinib','venetoclax','risdiplam','trastuzumab',
        'nusinersen','sofosbuvir','lecanemab','elranatamab','remdesivir'
      )
      ORDER BY d.normalized_name;
    """)
    print(df.to_string(index=False))
    section(md, "6a. Known-drug spot check", to_md(df))

    print("\n(6b) Known-indication spot check")
    df = q(conn, """
      SELECT i.display_name AS indication, ibc.bio_area, ibc.confidence
      FROM preclin.indication i
      LEFT JOIN preclin.indication_bio_class ibc USING(indication_id)
      WHERE i.display_name IN (
        'Type 2 diabetes','Alzheimer''s disease','Rheumatoid arthritis',
        'Hemophilia A','HIV','Non-small cell lung cancer',
        'Sickle cell disease','Duchenne muscular dystrophy','Hypertension',
        'Migraine','COVID-19','Depression','Asthma','Osteoporosis'
      )
      ORDER BY i.display_name;
    """)
    print(df.to_string(index=False))
    section(md, "6b. Known-indication spot check", to_md(df))

    # ─── 7. Orphans and integrity ──────────────────────────────────────────
    print("\n(7) Orphans")
    df = q(conn, """
      SELECT 'Drugs in ≥1 program without drug_bio_class' AS check_name,
             COUNT(DISTINCT p.drug_id) AS n
      FROM preclin.program p
      LEFT JOIN preclin.drug_bio_class dbc ON dbc.drug_id = p.drug_id
      WHERE dbc.drug_id IS NULL
      UNION ALL SELECT 'Indications in ≥1 program without indication_bio_class',
        COUNT(DISTINCT p.indication_id)
      FROM preclin.program p
      LEFT JOIN preclin.indication_bio_class ibc ON ibc.indication_id = p.indication_id
      WHERE ibc.indication_id IS NULL
      UNION ALL SELECT 'Programs without an outcome',
        COUNT(*) FROM preclin.program p
        LEFT JOIN preclin.program_outcome po ON po.program_id = p.program_id
        WHERE po.program_id IS NULL
      UNION ALL SELECT 'Approvals not linked to any program',
        COUNT(*) FROM preclin.approval a
        LEFT JOIN preclin.program p
          ON p.drug_id = a.drug_id AND p.indication_id = a.indication_id
        WHERE p.program_id IS NULL;
    """)
    print(df.to_string(index=False))
    section(md, "7. Orphans and integrity checks",
            to_md(df))

    # ─── 8. Silent-vs-direct signal breakdown ─────────────────────────────
    print("\n(8) Silent (inferred) vs direct (classified) fail signal")
    df = q(conn, """
      WITH trial_class AS (
        SELECT DISTINCT ON (c.subject_key) c.subject_key AS nct_id, c.category
        FROM preclin.classification c
        WHERE c.classifier_task = 'why_stopped' AND c.subject_type = 'trial'
        ORDER BY c.subject_key,
          CASE c.classifier_model WHEN 'claude-sonnet' THEN 1 ELSE 2 END
      ),
      program_reasons AS (
        SELECT pt.program_id, BOOL_OR(tc.category IS NOT NULL) AS has_any_reason
        FROM preclin.program_trial pt
        LEFT JOIN trial_class tc ON tc.nct_id = pt.nct_id
        GROUP BY pt.program_id
      )
      SELECT po.outcome_broad,
             COUNT(*) FILTER (WHERE pr.has_any_reason) AS with_direct_signal,
             COUNT(*) FILTER (WHERE NOT pr.has_any_reason) AS silent_only,
             COUNT(*) AS total
      FROM preclin.program p
      JOIN preclin.program_outcome po ON po.program_id = p.program_id
      LEFT JOIN program_reasons pr ON pr.program_id = p.program_id
      GROUP BY po.outcome_broad ORDER BY total DESC;
    """)
    print(df.to_string(index=False))
    section(md, "8. Silent (inference-only) vs direct (why_stopped-classified) fail signal",
            to_md(df))

    # ─── 9. Comparison to published (compute key rates) ───────────────────
    print("\n(9) Comparison to published benchmarks")
    df = q(conn, """
      WITH activity AS (
        SELECT pt.program_id,
          BOOL_OR(t.status IN ('RECRUITING','ACTIVE_NOT_RECRUITING',
                               'ENROLLING_BY_INVITATION','NOT_YET_RECRUITING')) AS active,
          MAX(COALESCE(t.completion_date, t.primary_completion_date, t.start_date)) AS latest
        FROM preclin.program_trial pt JOIN public.trials t USING(nct_id)
        GROUP BY pt.program_id
      ),
      cohort AS (
        SELECT p.program_id, p.highest_phase, po.outcome_broad
        FROM preclin.program p
        JOIN preclin.program_outcome po ON po.program_id = p.program_id
        LEFT JOIN activity a ON a.program_id = p.program_id
        WHERE (a.active IS NULL OR a.active = FALSE)
          AND po.outcome_broad != 'unknown'
          AND p.highest_phase >= 1
          AND (
            po.outcome_broad IN ('approved','efficacy_fail','safety_fail','commercial_fail',
                                  'enrollment_fail','unclassified_termination','planned_termination')
            OR (po.outcome_broad IN ('phase1_only','presumptive_fail_ph2','presumptive_efficacy_fail_ph3')
                AND a.latest < '2024-07-01')
          )
      )
      SELECT 'Ph1→Ph2 %' AS metric,
        ROUND(100.0 * COUNT(*) FILTER (WHERE highest_phase >= 2
                                         OR (highest_phase=1 AND outcome_broad='approved'))
                    / NULLIF(COUNT(*) FILTER (WHERE highest_phase >= 1), 0), 1) AS our_rate,
        '52.0' AS bio_2021, '66' AS wong_2019
      FROM cohort
      UNION ALL SELECT 'Ph2→Ph3 %',
        ROUND(100.0 * COUNT(*) FILTER (WHERE highest_phase >= 3
                                         OR (highest_phase=2 AND outcome_broad='approved'))
                    / NULLIF(COUNT(*) FILTER (WHERE highest_phase >= 2), 0), 1),
        '28.9', '29' FROM cohort
      UNION ALL SELECT 'Ph3→Approval %',
        ROUND(100.0 * COUNT(*) FILTER (WHERE outcome_broad='approved' AND highest_phase >= 3)
                    / NULLIF(COUNT(*) FILTER (WHERE highest_phase >= 3), 0), 1),
        '~52 (composed)', '58' FROM cohort
      UNION ALL SELECT 'Ph1→Approval (LOA)',
        ROUND(100.0 * COUNT(*) FILTER (WHERE outcome_broad='approved')
                    / NULLIF(COUNT(*) FILTER (WHERE highest_phase >= 1), 0), 1),
        '7.9', '13.8' FROM cohort;
    """)
    print(df.to_string(index=False))
    section(md, "9. Key transition rates vs published benchmarks",
            to_md(df))

    # Write markdown
    out = os.path.join(DATA, "data_audit.md")
    with open(out, "w") as f:
        f.write("\n".join(md))
    print(f"\nwrote {out}")
    conn.close()


if __name__ == "__main__":
    main()
